/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Dimeji
 */
public class ContactGui extends javax.swing.JFrame {

    private ArrayList<Dcontact> cList;
    private String subject;
    private String comment;
    private int count;
    boolean backToAssTech;

    /**
     * Creates new form ContactGui
     */
    public ContactGui(boolean comingFromAssTech) {
        backToAssTech = comingFromAssTech;
        initComponents();
        setLocationRelativeTo(null);
        cList = new ArrayList<Dcontact>();
        subject = new String();
        comment = new String();
        count = 0;



    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        Logo = new javax.swing.JLabel();
        Text = new javax.swing.JLabel();
        SubT = new javax.swing.JLabel();
        SubTF = new javax.swing.JTextField();
        Comment = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        CommTF = new javax.swing.JTextPane();
        Submit = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        Display = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        Backround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/white nci logo small.png"))); // NOI18N
        Logo.setText(" ");
        Logo.setBounds(20, 10, 240, 170);
        jLayeredPane1.add(Logo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Text.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        Text.setForeground(new java.awt.Color(255, 153, 0));
        Text.setText(" Contact");
        Text.setBounds(140, 200, 160, 40);
        jLayeredPane1.add(Text, javax.swing.JLayeredPane.DEFAULT_LAYER);

        SubT.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        SubT.setForeground(new java.awt.Color(255, 153, 0));
        SubT.setText("Subject:");
        SubT.setBounds(40, 240, 80, 60);
        jLayeredPane1.add(SubT, javax.swing.JLayeredPane.DEFAULT_LAYER);

        SubTF.setText(" ");
        SubTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubTFActionPerformed(evt);
            }
        });
        SubTF.setBounds(140, 260, 210, 30);
        jLayeredPane1.add(SubTF, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Comment.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Comment.setForeground(new java.awt.Color(255, 153, 0));
        Comment.setText("Comment's:");
        Comment.setBounds(20, 340, 120, 40);
        jLayeredPane1.add(Comment, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane1.setViewportView(CommTF);

        jScrollPane1.setBounds(140, 350, 210, 190);
        jLayeredPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Submit.setText("Submit");
        Submit.setFocusPainted(false);
        Submit.setOpaque(false);
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        Submit.setBounds(140, 550, 80, 22);
        jLayeredPane1.add(Submit, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Clear.setText("Clear");
        Clear.setFocusPainted(false);
        Clear.setOpaque(false);
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        Clear.setBounds(270, 550, 70, 22);
        jLayeredPane1.add(Clear, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Display.setText("Display");
        Display.setFocusPainted(false);
        Display.setOpaque(false);
        Display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayActionPerformed(evt);
            }
        });
        Display.setBounds(50, 440, 80, 22);
        jLayeredPane1.add(Display, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/back-arrow2 black and red.png"))); // NOI18N
        jButton5.setToolTipText("");
        jButton5.setOpaque(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.setBounds(10, 720, 74, 72);
        jLayeredPane1.add(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Backround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Math 2 wallpaper_1.jpg"))); // NOI18N
        Backround.setText(" ");
        Backround.setBounds(0, 0, 480, 800);
        jLayeredPane1.add(Backround, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed

        subject = SubTF.getText();
        comment = CommTF.getText();

        Dcontact c = new Dcontact();
        c.setSubject(subject);
        c.setComment(comment);



        File outFile;
        FileWriter fw;
        BufferedWriter bw;
        if (subject.equalsIgnoreCase(" ") || comment.equalsIgnoreCase(" ")) {
            JOptionPane.showMessageDialog(null, "Please fill in contact form");
        } else {

            try {
                outFile = new File("Student Subject.txt");
                fw = new FileWriter(outFile);
                bw = new BufferedWriter(fw);

                bw.write(subject);

                bw.close();
                JOptionPane.showMessageDialog(null, "Subject has been successfully saved to file");
            } catch (IOException e) {
                System.out.println("Error writing file" + e);
            }
        }
        cList.add(c);

        count++;

    }//GEN-LAST:event_SubmitActionPerformed

    private void SubTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubTFActionPerformed

    private void DisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayActionPerformed
        for (int i = 0; i < cList.size(); i++) {
            JOptionPane.showMessageDialog(null, "Subject: " + cList.get(i).getSubject() + "\n Comment: " + cList.get(i).getComment());
        }

    }//GEN-LAST:event_DisplayActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        CommTF.setText(" ");
        SubTF.setText(" ");
    }//GEN-LAST:event_ClearActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (backToAssTech) {
            AssistiveTechnology at = new AssistiveTechnology();
            at.setVisible(true);
        } else {
            Disability myD = new Disability();
            myD.setVisible(true);
        }

        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContactGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContactGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContactGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContactGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ContactGui(false).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Backround;
    private javax.swing.JButton Clear;
    private javax.swing.JTextPane CommTF;
    private javax.swing.JLabel Comment;
    private javax.swing.JButton Display;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel SubT;
    private javax.swing.JTextField SubTF;
    private javax.swing.JButton Submit;
    private javax.swing.JLabel Text;
    private javax.swing.JButton jButton5;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
