/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.io.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Ian
 */
public class Contact extends javax.swing.JFrame {
    //Creating the Array List and data members
    private ArrayList <Contac> alist;
    private String Comments, Subject,Name,Number;
    private int count;

    /**
     * Creates new form Contact
     */
    public Contact() {
        initComponents();
        setLocationRelativeTo(null);
        
        //Contructor for Array list 
        alist = new ArrayList <Contac>();
        Comments = new String();
        Subject = new String ();
        count = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        Logo = new javax.swing.JLabel();
        SubT = new javax.swing.JLabel();
        Sub = new javax.swing.JTextField();
        Comment = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Comm = new javax.swing.JTextPane();
        Text = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        SavedV = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        Backround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/white nci logo small.png"))); // NOI18N
        Logo.setText(" ");
        Logo.setBounds(20, 10, 240, 170);
        jLayeredPane1.add(Logo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        SubT.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        SubT.setForeground(new java.awt.Color(255, 153, 0));
        SubT.setText("Subject:");
        SubT.setBounds(40, 240, 80, 60);
        jLayeredPane1.add(SubT, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Sub.setText(" ");
        Sub.setBounds(140, 260, 210, 30);
        jLayeredPane1.add(Sub, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Comment.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Comment.setForeground(new java.awt.Color(255, 153, 0));
        Comment.setText("Comment's:");
        Comment.setBounds(20, 340, 120, 40);
        jLayeredPane1.add(Comment, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane1.setViewportView(Comm);

        jScrollPane1.setBounds(140, 350, 210, 190);
        jLayeredPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Text.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        Text.setForeground(new java.awt.Color(255, 153, 0));
        Text.setText(" Contact");
        Text.setBounds(140, 200, 160, 40);
        jLayeredPane1.add(Text, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2.setText("Display");
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setBounds(40, 430, 80, 22);
        jLayeredPane1.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton3.setText("Submit");
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.setBounds(140, 550, 80, 22);
        jLayeredPane1.add(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/back-arrow2 black and red.png"))); // NOI18N
        jButton1.setOpaque(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(40, 723, 72, 74);
        jLayeredPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        SavedV.setText("<html>View<br>Pervious<br>Commments\n         ");
        SavedV.setFocusPainted(false);
        SavedV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavedVActionPerformed(evt);
            }
        });
        SavedV.setBounds(40, 470, 80, 60);
        jLayeredPane1.add(SavedV, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Clear.setText("Clear");
        Clear.setFocusPainted(false);
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        Clear.setBounds(260, 550, 90, 22);
        jLayeredPane1.add(Clear, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Backround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Math 2 wallpaper.jpg"))); // NOI18N
        Backround.setText(" ");
        Backround.setBounds(0, 0, 480, 800);
        jLayeredPane1.add(Backround, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        Comments = Comm.getText();
        Subject =  Sub.getText();
        
        
        
        File inFile;
        FileReader fr;
        BufferedReader br;

        
        if (Comments.equalsIgnoreCase(" ") || Subject.equalsIgnoreCase(" ")){
            JOptionPane.showMessageDialog(null,"Please fiil in contact form");
        
        }
        else{
        try {
            inFile = new File("username.txt");
            fr = new FileReader(inFile);
            br = new BufferedReader(fr);

            Name = br.readLine();
            
                
            
            br.close();
        } catch (IOException e) {
            System.out.println(e);
        }
        

        try {
            inFile = new File("usernumber.txt");
            fr = new FileReader(inFile);
            br = new BufferedReader(fr);

            Number= br.readLine();
            
                
            
            br.close();
        } catch (IOException e) {
            System.out.println(e);
        }
        
        
       
        Contac F = new Contac(Comments,Subject,Name,Number);
        alist.add(F);
     
    
        
        File outFile;
        FileOutputStream fStream;
        ObjectOutputStream oStream;
        
        try{
            outFile = new File("out.data");
            fStream = new FileOutputStream(outFile);
            oStream = new ObjectOutputStream(fStream);
            
            oStream.writeObject(alist);
            
            
            
            oStream.close();
        }
        catch(IOException e){
            System.out.println(e);
        }
     
        }
     
    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          for(int i = 0; i<alist.size();i++){
            JOptionPane.showMessageDialog(null,"Your Comment was:  "+ alist.get(i).getComments()+"\nSubject:   "+ alist.get(i).getSubject());
            
            
         
    }//GEN-LAST:event_jButton2ActionPerformed
    }
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Quiz f = new Quiz();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SavedVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavedVActionPerformed
         File inFile;
        FileInputStream fStream;
        ObjectInputStream oStream;
        
        try{
            inFile = new File("out.data");
            fStream = new FileInputStream(inFile);
            oStream = new ObjectInputStream(fStream);
            
            /*Assessment x;
            x = (Assessment)oStream.readObject();*/
            ArrayList <Contac> xList;
            xList = (ArrayList<Contac>)oStream.readObject();
            for(Contac x:xList){
            JOptionPane.showMessageDialog(null, "\nName: "+x.getName()+"\nStudent Number : "+x.getNumber()+"\nSubject: "+x.getSubject()+"\nComment: "+x.getComments());
            }
            
            oStream.close();
        }
        catch(IOException e){
            System.out.println(e);
        }
        catch(ClassNotFoundException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_SavedVActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        Sub.setText(" ");
        Comm.setText(" ");
    }//GEN-LAST:event_ClearActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Contact().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Backround;
    private javax.swing.JButton Clear;
    private javax.swing.JTextPane Comm;
    private javax.swing.JLabel Comment;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton SavedV;
    private javax.swing.JTextField Sub;
    private javax.swing.JLabel SubT;
    private javax.swing.JLabel Text;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
