/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Ian
 */
public class Dyslexia extends javax.swing.JFrame {

    /**
     * Creates new form Dyslexia
     */
    public Dyslexia() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        Logo = new javax.swing.JLabel();
        Mk = new javax.swing.JLabel();
        Quiz = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        Text = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        Backround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/white nci logo small.png"))); // NOI18N
        Logo.setText("jLabel1");
        Logo.setBounds(20, 20, 240, 160);
        jLayeredPane1.add(Logo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Mk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/12222.png"))); // NOI18N
        Mk.setText("jLabel1");
        Mk.setBounds(340, 0, 140, 130);
        jLayeredPane1.add(Mk, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Quiz.setText("Quiz");
        Quiz.setFocusPainted(false);
        Quiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuizActionPerformed(evt);
            }
        });
        Quiz.setBounds(343, 713, 100, 70);
        jLayeredPane1.add(Quiz, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Title.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("Dyslexia");
        Title.setBounds(170, 180, 80, 50);
        jLayeredPane1.add(Title, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Text.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        Text.setForeground(new java.awt.Color(255, 204, 0));
        Text.setText("<html>Dyslexia screening is a new service being operated free of charge for all students in NCI. <br>The screening is suggested to students who feel that they may have difficulty with reading, writing, spelling or comprehension.<br>To avail of the service please complete the following survey and bring a printed version to the Learning Support Office (Room 3:11)");
        Text.setBounds(10, 240, 290, 440);
        jLayeredPane1.add(Text, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/back-arrow2 black and red.png"))); // NOI18N
        Back.setOpaque(false);
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        Back.setBounds(20, 710, 74, 72);
        jLayeredPane1.add(Back, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Backround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Math 2 wallpaper.jpg"))); // NOI18N
        Backround.setText(" ");
        Backround.setBounds(0, 0, 480, 800);
        jLayeredPane1.add(Backround, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        LearnD myLearn = new LearnD ();
        myLearn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void QuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuizActionPerformed
        Quiz Q = new Quiz();
        Q.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_QuizActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dyslexia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dyslexia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dyslexia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dyslexia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dyslexia().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel Backround;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Mk;
    private javax.swing.JButton Quiz;
    private javax.swing.JLabel Text;
    private javax.swing.JLabel Title;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
