/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JOptionPane;

/**
 *
 * @author Ian
 */
public class Harvard extends javax.swing.JFrame {

    /**
     * Creates new form Harvard
     */
    public Harvard() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        Logo = new javax.swing.JLabel();
        Mk = new javax.swing.JLabel();
        HarVid = new javax.swing.JButton();
        Moodle = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        Text = new javax.swing.JLabel();
        Backround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/white nci logo small.png"))); // NOI18N
        Logo.setText(" ");
        Logo.setBounds(10, 10, 240, 170);
        jLayeredPane1.add(Logo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Mk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/12222.png"))); // NOI18N
        Mk.setText(" ");
        Mk.setBounds(310, 50, 140, 120);
        jLayeredPane1.add(Mk, javax.swing.JLayeredPane.DEFAULT_LAYER);

        HarVid.setText("Harvard Video");
        HarVid.setFocusPainted(false);
        HarVid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HarVidActionPerformed(evt);
            }
        });
        HarVid.setBounds(160, 470, 160, 70);
        jLayeredPane1.add(HarVid, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Moodle.setText("Moodle");
        Moodle.setFocusPainted(false);
        Moodle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoodleActionPerformed(evt);
            }
        });
        Moodle.setBounds(330, 710, 120, 70);
        jLayeredPane1.add(Moodle, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/back-arrow2 black and red.png"))); // NOI18N
        Back.setOpaque(false);
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        Back.setBounds(20, 710, 74, 72);
        jLayeredPane1.add(Back, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Title.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("Harvard Style");
        Title.setBounds(160, 210, 130, 50);
        jLayeredPane1.add(Title, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Text.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        Text.setForeground(new java.awt.Color(255, 204, 0));
        Text.setText("<html>Welcome to the Harvard Referncing page,<br> here you will find a link to my youtube video i have uploaded,<br> to go  into detail about  the ways in Harvard Referncing.</html>");
        Text.setBounds(20, 270, 430, 180);
        jLayeredPane1.add(Text, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Backround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Math 2 wallpaper.jpg"))); // NOI18N
        Backround.setText(" ");
        Backround.setBounds(0, 0, 480, 800);
        jLayeredPane1.add(Backround, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HarVidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HarVidActionPerformed
        try{
            
            
            String URL ="http://www.youtube.com/watch?v=s3Jqc7WGrrE";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
        
        
        }
    }//GEN-LAST:event_HarVidActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        LearnD myLearn = new LearnD ();
        myLearn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void MoodleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoodleActionPerformed
        try{
            
            
            String URL ="https://moodle.ncirl.ie/login/index.php";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
        
        
        }
    }//GEN-LAST:event_MoodleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Harvard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Harvard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Harvard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Harvard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Harvard().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel Backround;
    private javax.swing.JButton HarVid;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Mk;
    private javax.swing.JButton Moodle;
    private javax.swing.JLabel Text;
    private javax.swing.JLabel Title;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
