/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import javax.swing.JOptionPane;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

/**
 *
 * @author Ian
 */
public class LearnS extends javax.swing.JFrame {

    boolean flag;

    /**
     * Creates new form LearnS
     */
    public LearnS() {
        initComponents();
        setLocationRelativeTo(null);
        flag = true;


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        Logo = new javax.swing.JLabel();
        Text = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        Egate = new javax.swing.JButton();
        Backround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/white nci logo small.png"))); // NOI18N
        Logo.setText("jLabel2");
        Logo.setBounds(20, 10, 240, 180);
        jLayeredPane1.add(Logo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Text.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Text.setForeground(new java.awt.Color(255, 204, 0));
        Text.setText("<html>The Learning Development Manual can provide you with the tools and advice to become a more effective learner in Higher Education.<br><br> Covering four units, the manual aims to help each student become aware of their learning style and to adopt an individual learning strategy.<br></html>");
        Text.setBounds(50, 260, 280, 220);
        jLayeredPane1.add(Text, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Title.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("Learning Info");
        Title.setBounds(120, 200, 200, 40);
        jLayeredPane1.add(Title, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setText("<html>Learning<br> Support<br> Audio");
        jButton1.setFocusPainted(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(310, 520, 120, 50);
        jLayeredPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/back-arrow2 black and red.png"))); // NOI18N
        Back.setOpaque(false);
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        Back.setBounds(20, 710, 74, 72);
        jLayeredPane1.add(Back, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Egate.setText("E-DysGate");
        Egate.setFocusPainted(false);
        Egate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EgateActionPerformed(evt);
            }
        });
        Egate.setBounds(150, 520, 100, 50);
        jLayeredPane1.add(Egate, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Backround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Math 2 wallpaper.jpg"))); // NOI18N
        Backround.setBounds(0, 0, 480, 800);
        jLayeredPane1.add(Backround, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //InputStream to stream the mp3 file
        InputStream in;
        
        //@ refenernce Music Player using java/netbeans.mp4
        // http://www.citethisforme.com/cite/online-image-or-video
        //try  catch and if statement
        try {
            //File input of 3.wav
            in = new FileInputStream(new File("3.wav"));
            AudioStream audio = new AudioStream(in);
           
            //if statement to only allow the file to play once until its finished
            // Using an boolean expression to decide if it can be played or not
            if (flag == true) {
                AudioPlayer.player.start(audio);
                flag = false;
                
              //False will mean it will stop audio  
            } else if(flag ==false){
                AudioPlayer.player.stop(audio);
                
            }
            //Catch here incase the file is unobtainable 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "If unable to get file, please visit the website " + "\n for more information");
        }
    
    }//GEN-LAST:event_jButton1ActionPerformed
    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        //Opens the gui LearnD which is the main menu
        //And close's this Gui
        LearnD myLearn = new LearnD ();
        myLearn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void EgateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EgateActionPerformed
        //Try catch statment  to open a website  using String URL
        try{

            String URL ="http://www.edysgate.org/site/index_main.php?lang=en&returnTo=";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());

        }
    }//GEN-LAST:event_EgateActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LearnS.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LearnS.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LearnS.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LearnS.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LearnS().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel Backround;
    private javax.swing.JButton Egate;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Text;
    private javax.swing.JLabel Title;
    private javax.swing.JButton jButton1;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
