/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Ian
 */
public class LearnD extends javax.swing.JFrame {

    /**
     * Creates new form LearnD
     */
    public LearnD() {
        initComponents();
        setLocationRelativeTo(null);
        //Setting the name of the user
        NameTf.setText("Hi "+Login.globalName);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        Logo = new javax.swing.JLabel();
        Mk = new javax.swing.JLabel();
        Contact = new javax.swing.JLabel();
        Text = new javax.swing.JLabel();
        NameTf = new javax.swing.JLabel();
        Har = new javax.swing.JButton();
        Dys = new javax.swing.JButton();
        LS = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        Moodle = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        Backround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/white nci logo small.png"))); // NOI18N
        Logo.setText(" ");
        Logo.setBounds(30, 20, 230, 150);
        jLayeredPane1.add(Logo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Mk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/12222.png"))); // NOI18N
        Mk.setText(" ");
        Mk.setBounds(280, 40, 140, 130);
        jLayeredPane1.add(Mk, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Contact.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Contact.setForeground(new java.awt.Color(255, 255, 255));
        Contact.setText("<html>\n<b>Learning Support tutor</b><br><br>\n<b>Contact</b>: Michael Goldrick\n<br>\n\n<b>Phone</b>: 01 6599245<br>\n<b>Email</b>: michael.goldrick@ncirl.ie");
        Contact.setBounds(280, 170, 190, 160);
        jLayeredPane1.add(Contact, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Text.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Text.setForeground(new java.awt.Color(255, 204, 0));
        Text.setText("<html>Here at National College of Ireland we believe that each student can have an effective and<br><br> enjoyable learning experience.  To ensure that this belief becomes practice, it is my goal to<br> <br>support all full-time, part-time and off-campus students in their academic studies.</html>");
        Text.setBounds(30, 380, 410, 200);
        jLayeredPane1.add(Text, javax.swing.JLayeredPane.DEFAULT_LAYER);

        NameTf.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        NameTf.setForeground(new java.awt.Color(255, 255, 255));
        NameTf.setText(" ");
        NameTf.setBounds(30, 230, 100, 30);
        jLayeredPane1.add(NameTf, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Har.setText("Harvard");
        Har.setFocusPainted(false);
        Har.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HarActionPerformed(evt);
            }
        });
        Har.setBounds(340, 610, 71, 50);
        jLayeredPane1.add(Har, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Dys.setText("Dyslexia");
        Dys.setFocusPainted(false);
        Dys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DysActionPerformed(evt);
            }
        });
        Dys.setBounds(190, 610, 90, 50);
        jLayeredPane1.add(Dys, javax.swing.JLayeredPane.DEFAULT_LAYER);

        LS.setText("<html>Learning<br> Info</html> ");
        LS.setFocusPainted(false);
        LS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LSActionPerformed(evt);
            }
        });
        LS.setBounds(50, 610, 73, 50);
        jLayeredPane1.add(LS, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/back-arrow2 black and red.png"))); // NOI18N
        Back.setOpaque(false);
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        Back.setBounds(50, 713, 74, 72);
        jLayeredPane1.add(Back, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Moodle.setText("Moodle");
        Moodle.setFocusPainted(false);
        Moodle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoodleActionPerformed(evt);
            }
        });
        Moodle.setBounds(340, 720, 70, 50);
        jLayeredPane1.add(Moodle, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Title.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("Learning Development");
        Title.setBounds(120, 320, 220, 50);
        jLayeredPane1.add(Title, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Backround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Math 2 wallpaper.jpg"))); // NOI18N
        Backround.setText(" ");
        Backround.setBounds(0, 0, 480, 800);
        jLayeredPane1.add(Backround, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DysActionPerformed
        //Opening the gui window dyslexia
        //And closing the gui window Learn D
        Dyslexia D = new Dyslexia();
        D.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DysActionPerformed

    private void HarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HarActionPerformed
        //Opening the Gui window Harvard
        //Closing the gui window  Learn D
        Harvard H = new Harvard();
        H.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HarActionPerformed

    private void MoodleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoodleActionPerformed
         
        //Try and catch statment  to open moodle website
        
        try{
            
            
            String URL ="https://moodle.ncirl.ie/login/index.php";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage());
        
        
        }
    }//GEN-LAST:event_MoodleActionPerformed

    private void LSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LSActionPerformed
       
        //Opening Gui window LearnS
        LearnS S = new LearnS();
        S.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LSActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        LearnMenu M = new LearnMenu();
        M.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LearnD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LearnD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LearnD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LearnD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LearnD().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel Backround;
    private javax.swing.JLabel Contact;
    private javax.swing.JButton Dys;
    private javax.swing.JButton Har;
    private javax.swing.JButton LS;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Mk;
    private javax.swing.JButton Moodle;
    private javax.swing.JLabel NameTf;
    private javax.swing.JLabel Text;
    private javax.swing.JLabel Title;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
