/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Ian
 */
public class Login extends javax.swing.JFrame {
    
    //Creating object
    private Lofo MyLofo;
    //Data members
    private String name;
    private String SNumber;
    protected static String globalName;

  

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        Logo = new javax.swing.JLabel();
        NameT = new javax.swing.JLabel();
        NameTf = new javax.swing.JTextField();
        Number = new javax.swing.JLabel();
        StuNum = new javax.swing.JTextField();
        Pro = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Backround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/white nci logo small.png"))); // NOI18N
        Logo.setText(" ");
        Logo.setBounds(10, 20, 250, 160);
        jLayeredPane1.add(Logo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        NameT.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        NameT.setForeground(new java.awt.Color(255, 255, 255));
        NameT.setText("Name");
        NameT.setBounds(30, 360, 110, 60);
        jLayeredPane1.add(NameT, javax.swing.JLayeredPane.DEFAULT_LAYER);

        NameTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTfActionPerformed(evt);
            }
        });
        NameTf.setBounds(140, 370, 280, 40);
        jLayeredPane1.add(NameTf, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Number.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        Number.setForeground(new java.awt.Color(255, 255, 255));
        Number.setText("<html>Student <br>Number</html>");
        Number.setBounds(20, 460, 110, 70);
        jLayeredPane1.add(Number, javax.swing.JLayeredPane.DEFAULT_LAYER);

        StuNum.setText(" ");
        StuNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StuNumActionPerformed(evt);
            }
        });
        StuNum.setBounds(140, 480, 280, 40);
        jLayeredPane1.add(StuNum, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Pro.setText("Proceed");
        Pro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProActionPerformed(evt);
            }
        });
        Pro.setBounds(313, 683, 130, 80);
        jLayeredPane1.add(Pro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        Exit.setBounds(33, 683, 130, 80);
        jLayeredPane1.add(Exit, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 0));
        jLabel2.setText("<html>Hi and welcome to the student support app<br> Please enter your details below</html>");
        jLabel2.setBounds(140, 210, 320, 120);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Backround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Math 2 wallpaper.jpg"))); // NOI18N
        Backround.setText(" ");
        Backround.setBounds(0, 0, 480, 800);
        jLayeredPane1.add(Backround, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTfActionPerformed
        
    }//GEN-LAST:event_NameTfActionPerformed

    private void ProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProActionPerformed
        // getting text from text fields
        
        name = NameTf.getText();        
        SNumber =StuNum.getText();
        
        //new object Lofo
        MyLofo = new Lofo(name,SNumber);
        globalName = name;
        //setting name and number
        MyLofo.setName(name);
        MyLofo.setNumber(SNumber);
        
        
        //Code for writing the file handling 
        File outFile;
        FileWriter fw;
        BufferedWriter bw;

        
       
        
        //Promting the user to input there Name and number
        //if they leave it empty 
        //The if Statment prompts the JOptionPane Dialog box
        if(name.equalsIgnoreCase ("") || SNumber.equalsIgnoreCase("")){
        JOptionPane.showMessageDialog(null,"Please enter your Name and Student Number");
        
        }
        else {
            // Writing the username txt using file handling
            // So it can be used later. 
            try {
            outFile = new File("username.txt");
            fw = new FileWriter(outFile );
            bw = new BufferedWriter(fw);

            bw.write(name);
            

            bw.close();
            
        } catch (IOException e) {
            System.out.println("Error writing to file: " + e);
        }try {
            // Writing the userNumber txt using file handling
            // So it can be used later. 
            outFile = new File("userNumber.txt");
            fw = new FileWriter(outFile);
            bw = new BufferedWriter(fw);

            bw.write(SNumber);
            

            bw.close();
            
            //JOptionPane Prompt
            JOptionPane.showMessageDialog(null, "Thank you for Logging in.");
        } catch (IOException e) {
            System.out.println("Error writing to file: " + e);
        }
        
        
        //Opening the gui window
        //Closing this the gui window using the dispose method
        LearnMenu Lm = new LearnMenu();
        Lm.setVisible(true);
        this.dispose();
         
        
        
        } 
        
            
        
        
        
        
            
        
        
        
        
    }//GEN-LAST:event_ProActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void StuNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StuNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StuNumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Backround;
    private javax.swing.JButton Exit;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel NameT;
    private javax.swing.JTextField NameTf;
    private javax.swing.JLabel Number;
    private javax.swing.JButton Pro;
    private javax.swing.JTextField StuNum;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
