/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 * Class name  MathHelpJFrame.java
 * @author Fiachra Devitt x12317886
 * Version 01
 * Date 04/04/2013
 */
import java.io.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
public class MathHelpJFrame extends javax.swing.JFrame {
       private ArrayList <Details> alist;
       private String StudentMail, StaffMail, Comment, Name, Number;
       private int count;
    /**
     * Creates new form MathHelpJFrame
     */
    public MathHelpJFrame() {
        initComponents();
        setLocationRelativeTo(null);
        alist = new ArrayList<>();
        StudentMail = new String();
        StaffMail = new String();
        Comment = new String();
        count = 0;
        
        
        
         String name;
        
          
        File inFile;
        FileReader fr;
        BufferedReader br;

        try {
            inFile = new File("userNumber.txt");
            fr = new FileReader(inFile);
            br = new BufferedReader(fr);

            name = br.readLine();
            
            br.close();
             while (name != null) {
                StudentEmail.setText(name+"@student.ncirl.ie");
                name = br.readLine();
            }
        } catch (IOException e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        StaffEmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        MsgBox = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        StudentEmail = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        SendBtn = new javax.swing.JButton();
        ViewBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/back-arrow2 black and red.png"))); // NOI18N
        jButton5.setToolTipText("");
        jButton5.setOpaque(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.setBounds(10, 720, 74, 72);
        jLayeredPane1.add(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/white nci logo small.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setBounds(10, 10, 230, 137);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        StaffEmail.setText("jonathan.lambert@ncirl.ie");
        StaffEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffEmailActionPerformed(evt);
            }
        });
        StaffEmail.setBounds(60, 310, 360, 30);
        jLayeredPane1.add(StaffEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);

        MsgBox.setColumns(20);
        MsgBox.setRows(5);
        jScrollPane1.setViewportView(MsgBox);

        jScrollPane1.setBounds(60, 380, 360, 280);
        jLayeredPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 204, 0));
        jLabel6.setText("Please write your query in the text field below:");
        jLabel6.setBounds(60, 350, 400, 20);
        jLayeredPane1.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        StudentEmail.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        StudentEmail.setForeground(new java.awt.Color(255, 255, 255));
        StudentEmail.setBounds(60, 240, 360, 30);
        jLayeredPane1.add(StudentEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 204, 0));
        jLabel8.setText("Staff Email:");
        jLabel8.setBounds(60, 280, 340, 20);
        jLayeredPane1.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        SendBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SendBtn.setText("Send");
        SendBtn.setFocusPainted(false);
        SendBtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        SendBtn.setOpaque(false);
        SendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendBtnActionPerformed(evt);
            }
        });
        SendBtn.setBounds(310, 670, 110, 40);
        jLayeredPane1.add(SendBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        ViewBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ViewBtn.setText("View previous");
        ViewBtn.setFocusPainted(false);
        ViewBtn.setMargin(new java.awt.Insets(0, 0, 0, 0));
        ViewBtn.setOpaque(false);
        ViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBtnActionPerformed(evt);
            }
        });
        ViewBtn.setBounds(60, 670, 150, 40);
        jLayeredPane1.add(ViewBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 204, 0));
        jLabel9.setText("Your Email:");
        jLabel9.setBounds(60, 210, 340, 20);
        jLayeredPane1.add(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Math 2 wallpaper.jpg"))); // NOI18N
        jLabel1.setBounds(0, 0, 480, 800);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        MathHomeJFrame myMH = new MathHomeJFrame();
        myMH.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void StaffEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StaffEmailActionPerformed

    private void SendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendBtnActionPerformed
//This button takes the information that the user has entered in the StudentEmail
//and StaffEmail JTextFields along with the information entered in the MsgBox 
//JTextArea and saves the info to a file called MathMsg.data

StaffMail = StaffEmail.getText();// TODO add your handling code here:
Comment = MsgBox.getText();

         File inFile;
        FileReader fr;
        BufferedReader br;

try {
            inFile = new File("usernumber.txt");
            fr = new FileReader(inFile);
            br = new BufferedReader(fr);

            Number= br.readLine();
            
                
            
            br.close();
        } catch (IOException e) {
            System.out.println(e);
        }
Details D = new Details(StudentMail,StaffMail,Comment, Name , Number);
D.setStudentMail(StudentMail);
D.setStaffMail(StaffMail);
D.setComment(Comment);
alist.add(D);
count++;

File outFile;
FileOutputStream fStream;
ObjectOutputStream oStream;

try{
    outFile = new File("MathMsg.data");
    fStream = new FileOutputStream(outFile);
    oStream = new ObjectOutputStream(fStream);
    
    oStream.writeObject(alist);
    
    
    oStream.close();
}
catch(IOException e){
    System.out.println(e);
}
    }//GEN-LAST:event_SendBtnActionPerformed

    private void ViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBtnActionPerformed
//This button recalls the data from MathMsg.data and displays the information to
//the user
    File inFile;
    FileInputStream fStream;
    ObjectInputStream oStream;
try{
    inFile = new File("MathMsg.data");
    fStream = new FileInputStream(inFile);
    oStream = new ObjectInputStream(fStream);
    
    ArrayList <Details> alist;
    alist = (ArrayList<Details>)oStream.readObject();
    for(Details i:alist){
        JOptionPane.showMessageDialog(null,"\nYour Email:  "+i.getNumber()+"@ncirl.ie"+"\n Staff Email:   "+i.getStaffMail()+"\n Your Query:  "+i.getComment());
    }
    oStream.close();
    }
    catch(IOException e){
        System.out.println(e);
    }
    catch(ClassNotFoundException ex){
    System.out.println(ex);
}
    

    }//GEN-LAST:event_ViewBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MathHelpJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MathHelpJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MathHelpJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MathHelpJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new MathHelpJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea MsgBox;
    private javax.swing.JButton SendBtn;
    private javax.swing.JTextField StaffEmail;
    private javax.swing.JLabel StudentEmail;
    private javax.swing.JButton ViewBtn;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
