/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Dimeji
 */
public class PortalQuiz extends javax.swing.JFrame {

    /**
     * Creates new form PortalQuiz
     */
    public PortalQuiz() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Y1 = new javax.swing.JRadioButton();
        N1 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        y2 = new javax.swing.JRadioButton();
        N2 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        Y3 = new javax.swing.JRadioButton();
        N3 = new javax.swing.JRadioButton();
        N4 = new javax.swing.JRadioButton();
        Y4 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Y5 = new javax.swing.JRadioButton();
        N5 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/back-arrow2 black and red.png"))); // NOI18N
        jButton5.setToolTipText("");
        jButton5.setOpaque(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.setBounds(10, 720, 74, 72);
        jLayeredPane1.add(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/white nci logo small.png"))); // NOI18N
        jLabel2.setText(" ");
        jLabel2.setBounds(10, 10, 240, 160);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 0));
        jLabel3.setText("<html>Are you familiar with linux?</html>");
        jLabel3.setBounds(10, 220, 210, 50);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup1.add(Y1);
        Y1.setForeground(new java.awt.Color(255, 204, 0));
        Y1.setText("Yes");
        Y1.setOpaque(false);
        Y1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Y1ActionPerformed(evt);
            }
        });
        Y1.setBounds(250, 230, 70, 23);
        jLayeredPane1.add(Y1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup1.add(N1);
        N1.setForeground(new java.awt.Color(255, 204, 0));
        N1.setText("No");
        N1.setOpaque(false);
        N1.setBounds(350, 230, 80, 23);
        jLayeredPane1.add(N1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 204, 0));
        jLabel5.setText("<html>Have you any experience with programming languages (HTML, Java, C/C++/C#, Ruby etc)</html>");
        jLabel5.setBounds(10, 290, 190, 60);
        jLayeredPane1.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup2.add(y2);
        y2.setForeground(new java.awt.Color(255, 204, 0));
        y2.setText("Yes");
        y2.setOpaque(false);
        y2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                y2ActionPerformed(evt);
            }
        });
        y2.setBounds(250, 300, 70, 23);
        jLayeredPane1.add(y2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup2.add(N2);
        N2.setForeground(new java.awt.Color(255, 204, 0));
        N2.setText("No");
        N2.setFocusable(false);
        N2.setOpaque(false);
        N2.setBounds(350, 300, 80, 23);
        jLayeredPane1.add(N2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 204, 0));
        jLabel6.setText("<html>Do you consider yourself to be accident prone or clumsy?</html>");
        jLabel6.setBounds(10, 380, 170, 50);
        jLayeredPane1.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup3.add(Y3);
        Y3.setForeground(new java.awt.Color(255, 204, 0));
        Y3.setText("Yes");
        Y3.setOpaque(false);
        Y3.setBounds(250, 390, 70, 23);
        jLayeredPane1.add(Y3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup3.add(N3);
        N3.setForeground(new java.awt.Color(255, 204, 0));
        N3.setText("No");
        N3.setOpaque(false);
        N3.setBounds(350, 390, 70, 23);
        jLayeredPane1.add(N3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup4.add(N4);
        N4.setForeground(new java.awt.Color(255, 204, 0));
        N4.setText("No");
        N4.setOpaque(false);
        N4.setBounds(350, 480, 70, 23);
        jLayeredPane1.add(N4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup4.add(Y4);
        Y4.setForeground(new java.awt.Color(255, 204, 0));
        Y4.setText("Yes");
        Y4.setOpaque(false);
        Y4.setBounds(250, 480, 70, 23);
        jLayeredPane1.add(Y4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 204, 0));
        jLabel7.setText("<html>Do you get frustated easily?</html>");
        jLabel7.setBounds(10, 470, 150, 60);
        jLayeredPane1.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 204, 0));
        jLabel8.setText("<html>Are you colourblind?</html>");
        jLabel8.setBounds(10, 570, 160, 60);
        jLayeredPane1.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup5.add(Y5);
        Y5.setForeground(new java.awt.Color(255, 204, 0));
        Y5.setText("Yes");
        Y5.setOpaque(false);
        Y5.setBounds(250, 590, 70, 23);
        jLayeredPane1.add(Y5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup5.add(N5);
        N5.setForeground(new java.awt.Color(255, 204, 0));
        N5.setText("No");
        N5.setOpaque(false);
        N5.setBounds(350, 590, 60, 23);
        jLayeredPane1.add(N5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 204));
        jLabel4.setText("Portal Quiz");
        jLabel4.setBounds(120, 170, 220, 50);
        jLayeredPane1.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setText("Submit");
        jButton1.setFocusPainted(false);
        jButton1.setOpaque(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(360, 710, 100, 80);
        jLayeredPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Math 2 wallpaper.jpg"))); // NOI18N
        jLabel1.setBounds(0, 0, 480, 800);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Y1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Y1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Y1ActionPerformed

    private void y2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_y2ActionPerformed

    }//GEN-LAST:event_y2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
ComputingSupport myComputing = new ComputingSupport();
        myComputing.setVisible(true); 
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        Y1.setSelected(false);
        N1.setSelected(false);
        y2.setSelected(false);
        N2.setSelected(false);
        Y3.setSelected(false);
        N3.setSelected(false);
        Y4.setSelected(false);
        N4.setSelected(false);
        Y5.setSelected(false);
        N5.setSelected(false);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PortalQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PortalQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PortalQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PortalQuiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PortalQuiz().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton N1;
    private javax.swing.JRadioButton N2;
    private javax.swing.JRadioButton N3;
    private javax.swing.JRadioButton N4;
    private javax.swing.JRadioButton N5;
    private javax.swing.JRadioButton Y1;
    private javax.swing.JRadioButton Y3;
    private javax.swing.JRadioButton Y4;
    private javax.swing.JRadioButton Y5;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JRadioButton y2;
    // End of variables declaration//GEN-END:variables
}
