/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.io.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
 

/**
 *
 * @author Ian
 */
public class Quiz extends javax.swing.JFrame {
    //Creating the Arraylist
    private ArrayList <QResults> aList;
    
   
    //data members
     String Ans1,Ans2,Ans3,Ans4;
     int count;
    /**
     * Creates new form Quiz
     */
    public Quiz() {
        initComponents();
        setLocationRelativeTo(null);
       //constructor for Arraylist and strings 
       aList = new ArrayList <QResults>();
       Ans1 = new String();
       Ans2 = new String();
       Ans3 = new String();
       Ans4 = new String();
       
       count = 0;   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        Logo = new javax.swing.JLabel();
        Q1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        Q2 = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        Q3 = new javax.swing.JLabel();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        ViewBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        backround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/white nci logo small.png"))); // NOI18N
        Logo.setText(" ");
        Logo.setBounds(20, 20, 250, 150);
        jLayeredPane1.add(Logo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Q1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Q1.setForeground(new java.awt.Color(255, 153, 0));
        Q1.setText("<html>Have you ever been diagnosed with dyslexia / dyspraxia / dyscalculia?</html>");
        Q1.setBounds(20, 200, 430, 40);
        jLayeredPane1.add(Q1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 153, 51));
        jRadioButton1.setText("Yes");
        jRadioButton1.setBounds(40, 250, 70, 23);
        jLayeredPane1.add(jRadioButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 153, 0));
        jRadioButton2.setText("No");
        jRadioButton2.setBounds(180, 250, 60, 23);
        jLayeredPane1.add(jRadioButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 153, 0));
        jRadioButton3.setText("Maybe");
        jRadioButton3.setBounds(330, 250, 90, 23);
        jLayeredPane1.add(jRadioButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Q2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Q2.setForeground(new java.awt.Color(255, 153, 0));
        Q2.setText("<html>Have you ever used a coloured overlay or had tinted lenses to help you with reading?</html>");
        Q2.setBounds(20, 300, 420, 50);
        jLayeredPane1.add(Q2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(255, 153, 0));
        jRadioButton4.setText("Yes");
        jRadioButton4.setBounds(40, 370, 70, 23);
        jLayeredPane1.add(jRadioButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton5.setForeground(new java.awt.Color(255, 153, 0));
        jRadioButton5.setText("No");
        jRadioButton5.setBounds(180, 370, 60, 23);
        jLayeredPane1.add(jRadioButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup2.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton6.setForeground(new java.awt.Color(255, 153, 0));
        jRadioButton6.setText("Maybe");
        jRadioButton6.setBounds(330, 370, 90, 23);
        jLayeredPane1.add(jRadioButton6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Q3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Q3.setForeground(new java.awt.Color(255, 153, 0));
        Q3.setText("<html>Do you consider yourself to be accident prone or clumsy?</html>");
        Q3.setBounds(30, 440, 360, 40);
        jLayeredPane1.add(Q3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup3.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton7.setForeground(new java.awt.Color(255, 153, 0));
        jRadioButton7.setText("Yes");
        jRadioButton7.setBounds(40, 500, 70, 23);
        jLayeredPane1.add(jRadioButton7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup3.add(jRadioButton8);
        jRadioButton8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton8.setForeground(new java.awt.Color(255, 153, 0));
        jRadioButton8.setText("No");
        jRadioButton8.setBounds(180, 500, 60, 23);
        jLayeredPane1.add(jRadioButton8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonGroup3.add(jRadioButton9);
        jRadioButton9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton9.setForeground(new java.awt.Color(255, 153, 0));
        jRadioButton9.setText("Maybe");
        jRadioButton9.setBounds(330, 500, 90, 23);
        jLayeredPane1.add(jRadioButton9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("<html>Do you find it hard to listen to and retain verbal information / spoken instructions?</html>");
        jLabel1.setBounds(40, 560, 390, 40);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jRadioButton10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton10.setForeground(new java.awt.Color(255, 153, 0));
        jRadioButton10.setText("Yes");
        jRadioButton10.setBounds(40, 630, 70, 23);
        jLayeredPane1.add(jRadioButton10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jRadioButton11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton11.setForeground(new java.awt.Color(255, 153, 0));
        jRadioButton11.setText("No");
        jRadioButton11.setBounds(180, 630, 60, 23);
        jLayeredPane1.add(jRadioButton11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jRadioButton12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton12.setForeground(new java.awt.Color(255, 153, 0));
        jRadioButton12.setText("Maybe");
        jRadioButton12.setBounds(330, 630, 90, 23);
        jLayeredPane1.add(jRadioButton12, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setText("Submit");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(120, 720, 70, 60);
        jLayeredPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/back-arrow2 black and red.png"))); // NOI18N
        Back.setOpaque(false);
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        Back.setBounds(20, 710, 74, 72);
        jLayeredPane1.add(Back, javax.swing.JLayeredPane.DEFAULT_LAYER);

        ViewBtn.setText("<html>View<br>Results");
        ViewBtn.setOpaque(false);
        ViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBtnActionPerformed(evt);
            }
        });
        ViewBtn.setBounds(200, 720, 73, 60);
        jLayeredPane1.add(ViewBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/help button take 1.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        jLabel7.setBounds(350, 700, 90, 84);
        jLayeredPane1.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton6.setText("jButton6");
        jButton6.setContentAreaFilled(false);
        jButton6.setFocusPainted(false);
        jButton6.setFocusable(false);
        jButton6.setRolloverEnabled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jButton6.setBounds(360, 720, 60, 50);
        jLayeredPane1.add(jButton6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        backround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Math 2 wallpaper.jpg"))); // NOI18N
        backround.setText(" ");
        backround.setBounds(0, 0, 480, 800);
        jLayeredPane1.add(backround, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //New Object QResults
        QResults Q = new QResults();
        
        
        // Question1 answer, selecting the button and grabbing the text
        if(jRadioButton1.isSelected()) {
            
            Ans1 = jRadioButton1.getText();
            Q.setAnswer1(Ans1);
             
          
           
             
            
        
             //increment counter
            
        
            
        } else if (jRadioButton2.isSelected()) {
            
            Ans1 = jRadioButton2.getText();
             Q.setAnswer1(Ans1);
             
        
             //increment counter
            
            
        }
        else if (jRadioButton3.isSelected()){
           
            Ans1 = jRadioButton3.getText();
             Q.setAnswer1(Ans1);
             
        
             //increment counter
            
        }
        // Question2 answer selecting the button and grabbing the text
        if(jRadioButton4.isSelected()) {
            
            Ans2 = jRadioButton4.getText();
             Q.setAnswer2(Ans2);
          
             //increment counter
         
            
            
        } else if (jRadioButton5.isSelected()) {
            
            Ans2 = jRadioButton5.getText();
             Q.setAnswer2(Ans2);
             
        
             //increment counter
           
            
            
        }
        else if (jRadioButton6.isSelected()){
            
            Ans2 = jRadioButton6.getText();
             Q.setAnswer2(Ans2);
             
        
             //increment counter
          
        
        }
        // Question3 answer selecting the button and grabbing the text
        if(jRadioButton7.isSelected()) {
            
            Ans3 = jRadioButton7.getText();
            Q.setAnswer3(Ans3);
            
        
             //increment counter
             
            
            
        } else if (jRadioButton8.isSelected()) {
            
            Ans3 = jRadioButton8.getText();
            Q.setAnswer3(Ans3);
             
        
             //increment counter
             
            
            
        }
        else if (jRadioButton9.isSelected()){
            
            Ans3 = jRadioButton9.getText();
            Q.setAnswer3(Ans3);
            
        
             //increment counter
             
        
        
        }
        // Question4 answer selecting the button and grabbing the text
        if(jRadioButton10.isSelected()) {
            
            Ans4 = jRadioButton10.getText();
            Q.setAnswer4(Ans4);
             
        
             //increment counter
            
            
            
        } else if (jRadioButton11.isSelected()) {
           
            Ans4 = jRadioButton11.getText();
            Q.setAnswer4(Ans4);
          
        
             //increment counter
            
            
            
        }
        else if (jRadioButton12.isSelected()){
            
            Ans4 = jRadioButton12.getText();
            Q.setAnswer4(Ans4);
             
        
             //increment counter
             
        
        
        }
        
        aList.add(Q);
        
         File outFile;
        FileOutputStream fStream;
        ObjectOutputStream oStream;
        
        try{
            outFile = new File("output.data");
            fStream = new FileOutputStream(outFile);
            oStream = new ObjectOutputStream(fStream);
            
            oStream.writeObject(aList);
            
            
            
            oStream.close();
        }
        catch(IOException e){
            System.out.println(e);
        }
        
        JOptionPane.showMessageDialog(null,"If you answered yes to any of these questions "+"\n You should fill out the form "+"\n and leave a messeage in contact "+"below "+"\n thank you.");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        Dyslexia myD = new Dyslexia ();
        myD.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void ViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBtnActionPerformed
        File inFile;
        FileInputStream fStream;
        ObjectInputStream oStream;
        
        try{
            inFile = new File("output.data");
            fStream = new FileInputStream(inFile);
            oStream = new ObjectInputStream(fStream);
            
            /*Assessment x;
            x = (Assessment)oStream.readObject();*/
            ArrayList <QResults> xList;
            xList = (ArrayList<QResults>)oStream.readObject();
            for(QResults x:xList){
            JOptionPane.showMessageDialog(null, "Answer one :   "+x.getAnswer1()+"\nAnswer two :   "+x.getAnswer2()+"\nAnswer three :    "+x.getAnswer3()+"\nAnswer Four:   "+x.getAnswer4());
            }
            
            oStream.close();
        }
        catch(IOException e){
            System.out.println(e);
        }
        catch(ClassNotFoundException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_ViewBtnActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       Contact C = new Contact();
       C.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quiz().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Q1;
    private javax.swing.JLabel Q2;
    private javax.swing.JLabel Q3;
    private javax.swing.JButton ViewBtn;
    private javax.swing.JLabel backround;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    // End of variables declaration//GEN-END:variables
}
